/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ResearchThreadIdRouteImport } from './routes/research.$threadId'
import { Route as ForumTopicIdRouteImport } from './routes/forum.$topicId'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as BodyIdRouteImport } from './routes/body.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicImageRouteImport } from './routes/api/public/image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchRoute,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForumRoute,
} as any)
const ResearchThreadIdRoute = ResearchThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ResearchRoute,
} as any)
const ForumTopicIdRoute = ForumTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => ForumRoute,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyIdRoute = BodyIdRouteImport.update({
  id: '/body/$id',
  path: '/body/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageRoute = ApiPublicImageRouteImport.update({
  id: '/api/public/image',
  path: '/api/public/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/forum': typeof ForumRouteWithChildren
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/research': typeof ResearchRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/body/$id': typeof BodyIdRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/research/$threadId': typeof ResearchThreadIdRoute
  '/forum/': typeof ForumIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/body/$id': typeof BodyIdRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/research/$threadId': typeof ResearchThreadIdRoute
  '/forum': typeof ForumIndexRoute
  '/research': typeof ResearchIndexRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/forum': typeof ForumRouteWithChildren
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/research': typeof ResearchRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/body/$id': typeof BodyIdRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/research/$threadId': typeof ResearchThreadIdRoute
  '/forum/': typeof ForumIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/forum'
    | '/login'
    | '/missions'
    | '/research'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/body/$id'
    | '/category/$category'
    | '/forum/$topicId'
    | '/research/$threadId'
    | '/forum/'
    | '/research/'
    | '/api/public/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/login'
    | '/missions'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/body/$id'
    | '/category/$category'
    | '/forum/$topicId'
    | '/research/$threadId'
    | '/forum'
    | '/research'
    | '/api/public/image'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/forum'
    | '/login'
    | '/missions'
    | '/research'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api/chat'
    | '/body/$id'
    | '/category/$category'
    | '/forum/$topicId'
    | '/research/$threadId'
    | '/forum/'
    | '/research/'
    | '/api/public/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ForumRoute: typeof ForumRouteWithChildren
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  BodyIdRoute: typeof BodyIdRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ApiPublicImageRoute: typeof ApiPublicImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/forum/': {
      id: '/forum/'
      path: '/'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof ForumRoute
    }
    '/research/$threadId': {
      id: '/research/$threadId'
      path: '/$threadId'
      fullPath: '/research/$threadId'
      preLoaderRoute: typeof ResearchThreadIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/forum/$topicId': {
      id: '/forum/$topicId'
      path: '/$topicId'
      fullPath: '/forum/$topicId'
      preLoaderRoute: typeof ForumTopicIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body/$id': {
      id: '/body/$id'
      path: '/body/$id'
      fullPath: '/body/$id'
      preLoaderRoute: typeof BodyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image': {
      id: '/api/public/image'
      path: '/api/public/image'
      fullPath: '/api/public/image'
      preLoaderRoute: typeof ApiPublicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ForumRouteChildren {
  ForumTopicIdRoute: typeof ForumTopicIdRoute
  ForumIndexRoute: typeof ForumIndexRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumTopicIdRoute: ForumTopicIdRoute,
  ForumIndexRoute: ForumIndexRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface ResearchRouteChildren {
  ResearchThreadIdRoute: typeof ResearchThreadIdRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchThreadIdRoute: ResearchThreadIdRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ForumRoute: ForumRouteWithChildren,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  ResearchRoute: ResearchRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  BodyIdRoute: BodyIdRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ApiPublicImageRoute: ApiPublicImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
